name: valor-pro-deploy-action
description: docker build and push action.
author: valor-pro 
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  kube_config:
    description: 'Username used to log against the Docker registry'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        #!/bin/bash

        #set -x
        set -e 
 
        uses() {
          [ ! -z "${1}" ]
        }

        function replace()
        {

            if [ "$1" == "SUBDOMAIN" ]; then
                set -x
            fi      
            if [ "$#" -ne 3 ]; then
                echo $1" set default"
                sed -i 's@${'$1'}@'"\"\""'@g' $2
            else
                sed -i 's@${'$1'}@'"$2"'@g' $3
            fi
            set +x
        }

        echo ${KUBE_CONFIG}  > /tmp/config

        export KUBECONFIG=/tmp/config 
        kubectl version
        kubectl get ns

        IMAGE_BASE_PATH=harbor.devops.valorpro.com.br/valor
        REPO_NAME=${{ github.event.repository.name }}

        if  [ uses "${IMAGE_TAG}" ]; then
            echo "usando image tag informada $IMAGE_TAG"
        else
            echo "usando image tag gerada $IMAGE_TAG"
            IMAGE_TAG=$(git log --format="%h" -n 1)
        fi
                
        IMAGE_NAME=$IMAGE_BASE_PATH/$REPO_NAME:$IMAGE_TAG       

      shell: bash
      env:
        KUBE_CONFIG: ${{ inputs.kube_config }}
        IMAGE_TAG: : ${{ inputs.image_tag }} 

