name: valor-pro-deploy-action
description: docker build and push action.
author: valor-pro 
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  image_tag:
    description: 'image_tag'
    required: false

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash 
    - run: script.sh
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.image_tag }} 
        REPO_NAME: ${{ github.event.repository.name }}

