name: valor-pro-deploy-action
description: docker build and push action.
author: valor-pro 
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  image_tag:
    description: 'image_tag'
    required: false
  kube_config:
    description: 'kube_config'
    required: true
  namespace:
    description: 'namespace'
    required: true
  slack_webhook_url:
    description: 'slack_webhook_url'
    required: false

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash 
    - run: script.sh
      shell: bash
      env:
        KUBE_CONFIG: ${{ inputs.kube_config }}      
        IMAGE_TAG: ${{ inputs.image_tag }} 
        REPO_NAME: ${{ github.event.repository.name }}
        NAMESPACE: ${{ inputs.namespace }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
